### PR TITLE
It can process any length of text without any recursion limit

### PR DESCRIPTION
**Pull request by Jarvisr**

### CODE REVIEW

**Comment by grantjenks** [comment]
Can you explain this comment?

```
+        # Append last 5 words for resegment 
+        # To resolve segmention problem in some cases
```

**Comment by Jarvisr** [comment]
Sure.

## Example: 
This is the text which need to precess. It's length is 259 char. 

### Input :
text="searchimagemapplayyoutubenewsgmaildrivecalendartranslatebookbloggerphotodocevenaccountoptionsignsearchsettingwebhistoryadvancedsearchlanguagetoolgooglecoinofferedadvertisingprogrambusinesssolutiongooglegooglegooglecomprivagooglegooglecomprivacyterm**independent**"

### Output (Not as expected):
['search', 'image', 'map', 'play', 'youtube', 'news', 'gmail', 'drive', 'calendar', 'translate', 'book', 'blogger', 'photo', 'doc', 'even', 'account', 'option', 'sign', 'search', 'setting', 'web', 'history', 'advanced', 'search', 'language', 'tool', 'google', 'coin', 'offered', 'advertising', 'program', 'business', 'solution', 'google', 'google', 'googlecom', 'priva', 'google', 'googlecom', 'privacy', 'term', **'in', 'dependent'**]

### Output (As expected):
['search', 'image', 'map', 'play', 'youtube', 'news', 'gmail', 'drive', 'calendar', 'translate', 'book', 'blogger', 'photo', 'doc', 'even', 'account', 'option', 'sign', 'search', 'setting', 'web', 'history', 'advanced', 'search', 'language', 'tool', 'google', 'coin', 'offered', 'advertising', 'program', 'business', 'solution', 'google', 'google', 'googlecom', 'priva', 'google', 'googlecom', 'privacy', 'term', **'independent'**]

## Explanation: 
Now if limit in segment function is 250 (segment(text,250)). Then last word independent is consider as "_in_" ( First iteration )and "_dependent_" ( Second iteration ). This not the output we want. So in my code append last 5 words - _('google', 'googlecom', 'privacy', 'term', 'in')_ -to next remaining character chunk -_(dependent)_ to resolve problem as above.

I hope this will help you to understand my comment.

**Comment by grantjenks** [comment]
Thanks for the explanation. I will try to get it in this week.

**Comment by grantjenks** [comment]
Thank you for the algorithm. I have incorporated your changes with improvements at d032edb and deployed at v0.8.0.

**Comment by Jarvisr** [comment]
At least you can mention my contribution. Never mind I am happy to help you.

**Pull request closed without merging**
